import { BRAND } from "@/lib/brand";

export const metadata = { title: `Terms & Conditions — ${BRAND.name}` };

const SECTIONS = [
  ["1. Acceptance", `By creating an account or using ${BRAND.name} (${BRAND.domain}) you agree to these Terms and Conditions. If you do not agree, please do not use the service.`],
  ["2. Eligibility", `You must be at least 21 years old to register and play. Only one account is permitted per person, phone number, household and device. ${BRAND.name} may request identity verification (KYC) at any time.`],
  ["3. Account", "You are responsible for keeping your login details secure. All activity on your account is your responsibility. Notify support immediately of any unauthorized use."],
  ["4. Deposits & Withdrawals", "Deposits are accepted via telebirr, CBE Birr, M-PESA and USDT. Withdrawals are paid to a method registered in your name. We may delay or refuse withdrawals pending verification or where fraud or abuse is suspected."],
  ["5. Bonuses", "Bonus funds are non-withdrawable and can only be used for wagering. One welcome bonus per player. Abuse of promotions may result in bonus forfeiture and account closure."],
  ["6. Games & Bets", "All game results are generated by certified RNG or provably fair algorithms. In the event of malfunction, all affected bets and payouts are void. Sports bets are settled on official results."],
  ["7. Responsible Gaming", "You can request deposit limits, time-outs or self-exclusion by contacting support. Gambling can be addictive — please play responsibly."],
  ["8. Changes", `${BRAND.name} may update these Terms at any time. Continued use of the service after changes constitutes acceptance.`],
  ["9. Contact", `For questions about these Terms contact ${BRAND.email}.`],
];

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl space-y-5 rounded-2xl bg-card p-6 sm:p-10">
      <h1 className="text-3xl font-black">Terms &amp; Conditions</h1>
      {SECTIONS.map(([h, p]) => (
        <section key={h}><h2 className="mb-1 font-bold">{h}</h2><p className="text-sm leading-relaxed text-mute">{p}</p></section>
      ))}
    </article>
  );
}
